# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "atlas"
type = "cli"

[platform.linux]
download-file = "atlas-community-linux-{arch}-v{version}"

[platform.macos]
download-file = "atlas-community-darwin-{arch}-v{version}"

[platform.windows]
download-file = "atlas-community-windows-{arch}-v{version}.exe"

[install]
download-url = "https://release.ariga.io/atlas/{download_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/ariga/atlas"
