# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "mockery"
type = "cli"

[platform.linux]
download-file = "mockery_{version}_Linux_{arch}.tar.gz"

[platform.macos]
download-file = "mockery_{version}_Darwin_{arch}.tar.gz"

[platform.windows]
download-file = "mockery_{version}_Windows_{arch}.tar.gz"

[install]
download-url = "https://github.com/vektra/mockery/releases/download/v{version}/{download_file}"
unpack = true

[install.arch]
aarch64 = "arm64"

[resolve]
git-url = "https://github.com/vektra/mockery"
