# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "fga"
type = "cli"

[platform.linux]
download-file = "fga_{version}_linux_{arch}.tar.gz"

[platform.macos]
download-file = "fga_{version}_darwin_{arch}.tar.gz"

[platform.windows]
download-file = "fga_{version}_windows_{arch}.tar.gz"

[install]
download-url = "https://github.com/openfga/cli/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/openfga/cli/releases/download/v{version}/checksums.txt"
unpack = true

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/openfga/cli"
