# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "tflint"
type = "cli"

[platform.linux]
download-file = "tflint_linux_{arch}.zip"

[platform.macos]
download-file = "tflint_darwin_{arch}.zip"

[platform.windows]
download-file = "tflint_windows_{arch}.zip"

[install]
download-url = "https://github.com/terraform-linters/tflint/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/terraform-linters/tflint/releases/download/v{version}/checksums.txt"
unpack = true

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"


[resolve]
git-url = "https://github.com/terraform-linters/tflint"
